### ISSUE TITLE
Bug to generate the Foreign key constraint during a migration if the property doesn't have the same name that the mysql colu

### ISSUE THREAD

**Issue by oom-** [loopbackio/loopback-connector-mysql#424]
##  Steps to reproduce

Create a model with foreign key + `belongsTo` decorator 
![image](https://user-images.githubusercontent.com/11071671/88406892-9632ec00-cdd1-11ea-9a2d-99cde775e1ef.png)

## Current Behavior

The migrate script crash because he looks for the name of the foreign key inside the props name of the object.
![image](https://user-images.githubusercontent.com/11071671/88407059-d4c8a680-cdd1-11ea-8b9a-555ed20b415b.png)

## Expected Behavior

Should just return the propName if not found instead of looking for `mysql` prop.

## Additional information

`win32 x64 12.16.1`
I will try to propose a fix

```js
 if (typeof modelToCheck.properties[propName] == 'undefined')
      return propName;
```

**Comment by agnes512** [comment]
@oom- thank you for your investigation! I was able to locate the problem real quick. I have submitted a PR to address the issue, thanks!

**Comment by agnes512** [comment]
@oom- I double checked it and found that there's something wrong with your relation definition. Since your foreign key is different from the default one, you will need to specify **the relation name** (see [docs](https://loopback.io/doc/en/lb4/BelongsTo-relation.html#relation-metadata)). For your case, it would be
```ts
@model({
  settings:{
        foreignKeys: {
      fk_order_customerId: {
        name: 'fk_branch_legalentity',
        entity: 'LegalEntity',
        entityKey: 'leId', // uses the PROP NAME instead of the actual column name
        foreignKey: 'leId',
      },
    },
  }
})
  @belongsTo(() => LegalEntity,
    {name: 'branch'}, // the relation name
    {mysql:{columnName: 'LE_ID'}}
    )
    leId: number;
```
Sorry that for some reasons I didn't spot it the first time 🤦  Could you try the definition and see if it works on your end? I am closing those PRs, and they can be reopened if it is actual a bug

**Comment by mathias22osterhagen22** [comment]
Hello, it doesn't work:

![image](https://user-images.githubusercontent.com/60438474/90518955-b30bd680-e167-11ea-9077-16ba55fb3b85.png)

![image](https://user-images.githubusercontent.com/60438474/90518991-c159f280-e167-11ea-97ec-e2fe5eef9b9f.png)

**Comment by agnes512** [comment]
@mathias22osterhagen22 is this the same error you got before?

**Comment by agnes512** [comment]
Some notes after checking it with exact same model / prop names:
1.
```
TypeError: Cannot read property 'mysql' of undefined
    at expectedColNameForModel (/Users/node_modules/loopback-connector-mysql/lib/migration.js:1025:51)
```
It throws this error when the source model PK is `leId`. `leid` works fine.

2. Something's wrong with the migration order. The error showed in https://github.com/strongloop/loopback-connector-mysql/issues/424#issuecomment-675479971 is because `LegalEntity` is not being migrated yet.

**Comment by agnes512** [comment]
Could you drop `Branches` and `LegalEntity` first then try `npm run build && npm run migrate`?

**Comment by agnes512** [comment]
Related issue: https://github.com/strongloop/loopback-next/issues/2831

**Comment by mathias22osterhagen22** [comment]
> @mathias22osterhagen22 is this the same error you got before?
Yes (sorry for the delay)
